# Generated by Django 4.2.6 on 2023-10-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('hall', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(null=True)),
                ('publisher', models.CharField(max_length=200)),
                ('isbn', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.author')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.shelf')),
            ],
        ),
    ]
